-- Generated by nwg-displays on 2026-06-28 at 01:10:46. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x0C29 0x00000067",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:Acer Technologies EK220Q J0 56090ECC43W01",
    mode = "1920x1080@120.0",
    position = "1920x0",
    scale = 1.0
})
