-- Generated by nwg-displays on 2026-06-27 at 17:22:39. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:BOE 0x0C29 0x00000067",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Acer Technologies EK220Q J0 56090ECC43W01",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:BOE 0x0C29 0x00000067"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Acer Technologies EK220Q J0 56090ECC43W01"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:BOE 0x0C29 0x00000067"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Acer Technologies EK220Q J0 56090ECC43W01"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:BOE 0x0C29 0x00000067"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "desc:Acer Technologies EK220Q J0 56090ECC43W01"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "desc:BOE 0x0C29 0x00000067"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "desc:Acer Technologies EK220Q J0 56090ECC43W01"
})
